//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sessia4.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public products()
        {
            this.realizations = new HashSet<realizations>();
        }
    
        public int id_prod { get; set; }
        public string name { get; set; }
        public Nullable<int> id_type_prod { get; set; }
        public string articul { get; set; }
        public Nullable<int> count_people_proizv { get; set; }
        public Nullable<int> number_ceh { get; set; }
        public Nullable<decimal> min_cost { get; set; }
    
        public virtual type_products type_products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<realizations> realizations { get; set; }
    }
}
