//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sessia4.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class realizations
    {
        public int id_realization { get; set; }
        public Nullable<int> id_prod { get; set; }
        public Nullable<int> id_agent { get; set; }
        public Nullable<System.DateTime> date_realiz { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual agents agents { get; set; }
        public virtual products products { get; set; }
    }
}
